spring:
  application:
    name: my-service
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          name: ${spring.application.name}
          service-base-url: http://localhost:8080
          management-base-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui
